#!/usr/bin/env bash
# Install HAProxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

config=\
"
frontend munjogu_frontend
        bind *:80
        option forwardfor
        mode http
        default_backend munjogu_backend

backend munjogu_backend
        balance roundrobin
        server 531535-web-01    54.237.4.65:80 check
        server 531535-web-02    18.233.64.247:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
