#!/usr/bin/env bash
# The script is displaying "Best School" 9 times and "Hi" on the ninth iteration

i=0
while ((i < 10))
do
    if ((i == 8))
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i += 1))
done
